
version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: cats_users_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cats_users_api
    restart: on-failure
    ports:
      - "8001:80"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=api_db
      - CAT_API_KEY=live_JBT0Ah0Nt12iyl2IpjQVLDWjcLk0GQwf4zI9wBMfmfejKmcC31mOJp4yJz5TsOUP
    depends_on:
      - mongodb

volumes:
  mongo_data:
